### ISSUE TITLE
adding ignore_changes option to source_code_hash 

### ISSUE THREAD

**Issue by igorinsky** [terraform-aws-modules/terraform-aws-lambda#131]
Hello,

Is there a way to ignore changes in source_code_hash to avoid rewriting the function with initial archive?
We would like to use this module, but to deploy new versions during CI process.

Any terraform apply reverts code back to initial.

**Comment by antonbabenko** [comment]
Hi!

There is no way to ignore changes in source_code_hash by design (we want Terraform to do updates as necessary).

Please make sure that you check [FAQ](https://github.com/terraform-aws-modules/terraform-aws-lambda#faq) where this question is answered.

If you still have problems using this module, make sure to provide terraform configuration you use (block `module` with parameters).

**Comment by igorinsky** [comment]
Hello,
Thank you for the very quick response!

Have switched to s3_existing_package and made a little update to CI to have an additional name (latest), so now it would take a proper one in case terraform apply is required.

Thanks again!

**Comment by antonbabenko** [comment]
Great, `s3_existing_package` is a very good option when running on CI. If you can use docker you can also build images and deploy them using this module (see [container-image example](https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/master/examples/container-image)).
