### ISSUE TITLE
Migrate policy statements to use list type

### ISSUE THREAD

**Issue by kamaz** [terraform-aws-modules/terraform-aws-lambda#194]
# Description

Migrate the `policy_statements` to use `list` over `map`. 

The reason for that is, `map` reshuffles the statements which create a confusing plan.

**Comment by kamaz** [comment]
Thanks for the quick response @antonbabenko and the link to the `code`. 

Yes, I've reviewed the code and when running locally all works as expected (Mac), a policy is not being shown as requires updating but when we run this through CI (`github actions`) the plan always/most of the time comes with a change to `policy`. 

I believe the reason for the above is that on different machines the order of the keys changes which causes changes to `JSON`. See https://discuss.hashicorp.com/t/does-map-sort-keys/12056. 

Let me play with a docker instance and try to run the plan against different containers to check if I can replicate what CI is doing.

**Comment by antonbabenko** [comment]
Correct, in most cases, it is related to the behavior implemented on the provider level (the way it creates a JSON from pieces).

I remember in the past we used to think twice about the correct order of elements to make sure that the solution works identically on all platforms or we would have to not use data-source but just a static json file (which is a bad idea here).

I am going to close this because I don't think we can do anything in this module.
