### ISSUE TITLE
Support lifecycle ignore changes for image_uri

### ISSUE THREAD

**Issue by giom-l** [terraform-aws-modules/terraform-aws-lambda#212]
All my lambdas are deployed as "dummy" lambda so that Terraform creates them and my CI handle the update of images running.
To be able to do that and not trigger a modification everytime terraform is run, I need terraform to set `ignore_changes` lifecycle set on `image_uri`.

I know that lifecycle support has already been required for modules (see https://github.com/hashicorp/terraform/issues/27360).
We couldn't also not make this module capable of handling all kind of lifecycle due to the number of resources handled.

However, there is an option to ignore updates on source_code_hash `ignore_source_code_hash` that let users get this ignore behaviour for other sources than container images.

Would it be possible to use this variable to also set 
```
lifecycle {
    ignore_changes = [
      image_uri
    ]
  }
```
when its value is `true` and get the same behaviour whatever kind of source we use ? 

That would be a minor change and it would'nt be (unless I'm wrong) with lifecycle support on module when it will be released.

**Comment by zamialloy** [comment]
Since [hashicorp/terraform#27360](https://github.com/hashicorp/terraform/issues/27360) is still not out, one solution that could work for everyone is adding a bool variable `ignore_image_uri` and using that to create a new `aws_lambda_function` resource. This resource will be identical to the current `aws_lambda_function.this` but the differences would be in the count and lifecycle policy.
```
resource "aws_lambda_function" "image_function" {
  count = local.create && var.create_function && !var.create_layer && var.ignore_image_uri ? 1 : 0
  lifecycle {
    ignore_changes = [image_uri]
  }
  ... (everything else exactly the same as aws_lambda_function.this)
  ...
}
```
This will ensure the new resource would only be created if that variable is specified.
All references to `aws_lambda_function.this[0]` would need to be updated. A local variable could be added as follows:
```
locals {
  ...
  lambda_used = var.ignore_image_uri ? aws_lambda_function.this[0] : aws_lambda_function.image_function[0]
} 
```
And all references to `aws_lambda_function.this[0]` can be replaced with `local.lambda_used` in main.tf, outputs.tf.

I have tried this out and it works.

The main drawback is that updates to the lambda resource would need to happen in two places going forward. Inside `aws_lambda_function.this` and `aws_lambda_function.image_function`
The other drawback is that if people were previously not using this variable and set it to true, they would need to use `terraform state mv` to migrate the resource to the correct block.

Let me know if this makes sense and is something we can move forward with.
