### ISSUE TITLE
PIP_REQUIRE_VIRTUALENV prevents lambda layer build when pip_requirements is needed

### ISSUE THREAD

**Issue by Nogginboink** [terraform-aws-modules/terraform-aws-lambda#222]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
Yes.
If a local environment variable PIP_REQUIRE_VIRTUALENV is set to true, pip will refuse to build the dependencies for a lambda layer if a virtualenv is not currently active. Having an active virtualenv is not necessary for all developers in all situations.

## Describe the solution you'd like.
Remove the environment setting before calling the pip requirements step. (Optionally, restore the setting after this step.)

## Describe alternatives you've considered.
Manually unsetting this environment variable is a usable workaround, but needs to be done per session which is a manual step I'd rather not have to do.

## Additional context
Hopefully this is a clear explanation. Should also hopefully be a low effort change.

**Comment by antonbabenko** [comment]
Such internal platform-specific settings are very tricky to handle and implement in Terraform modules because Terraform was not designed for anything like that.

A good practice (or a rule of thumb) for this module, is to use existing building&packaging features if they work for your case, and look into building docker images (eg. using [docker-build module](https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/master/modules/docker-build)) or even build externally, as soon as standard capabilities are not sufficient for the use-case.

So, I am going to close this issue.
