### ISSUE TITLE
Multiple Users Cause lambda.null_resource.archive[0] timestamp Differences

### ISSUE THREAD

**Issue by gugaiz** [terraform-aws-modules/terraform-aws-lambda#323]
## Description
I am experiencing the exact same issue explained [here](https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/63).

The solution provided was to upgrade to [v1.26.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v1.26.0) but I am using v3.3.1, is this a regression?

**Comment by deybhayden** [comment]
I'm seeing this same behavior.

- Module Version: `3.3.1`
- Terraform Version: `v1.2.3`

**Comment by KajiMaster** [comment]
Same too; was hoping I was doing something wrong.

Module Version: 3.3.1
Terrafomr Version v1.2.2

**Comment by KajiMaster** [comment]
I was able to remedy this with the solution in https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/51#issuecomment-681978205
Basically recreate_missing_package = false in the module puts a warning message in the timestamp; effectively disabling time as a measure to recreate. Doesn't prevent new packages from being build like it claims. Needs better wording as a solution for this issue related to 'timestamp'

**Comment by antonbabenko** [comment]
> @KajiMaster said: "Doesn't prevent new packages from being build like it claims."

I just double-checked it again and I see the same expected behavior as before. After the package has been created and `recreate_missing_package = false` is specified, there won't be new zip-files created inside of `builds` directory on sequential `terraform apply` runs.

I am not sure how flexible timestamp tracking can be. Currently, it is either `Yes` (content will be checked based on timestamp, and the package will be recreated, if missing) or `No` (no timestamp will be compared).

Will it help, if a user can choose to track drift using an argument like `hash` (see #331) instead of `timestamp` like now?

**Comment by savitafulmali** [comment]
I have added recreate_missing_package = false still terraform plan shows changes.
Is it work only for terraform apply command.?
