### ISSUE TITLE
support node.js 18 runtime

### ISSUE THREAD

**Issue by bnusunny** [terraform-aws-modules/terraform-aws-lambda#382]
Lambda supports Node.js 18 runtime. It would be good to support nodejs18.x in this module.

https://aws.amazon.com/about-aws/whats-new/2022/11/aws-lambda-support-node-js-18/

**Comment by deepesh-bex** [comment]
@antonbabenko is there any plan for this one?

**Comment by matheushr97** [comment]
Still missing nodejs18 support

**Comment by antonbabenko** [comment]
All runtimes are supported by this module automatically because we don't control what the user specifies in `runtime` argument here https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/complete/main.tf#L25

Try setting "nodejs18.x" (or whatever AWS allows) as a value of `runtime`.
